### ISSUE TITLE
Is it possible to highlight full text?

### ISSUE THREAD

**Issue by mankeomorakort** [nithril/lucene-generic-highlighter#1]
Hi Nicolas, I am looking for a solution to highlight full text as below:

Full Text: "the law on addendum to the law on audit of the Kingdom of Cambodia"
Query: "law on audit of the Kingdom of Cambodia"
Expected Result:   "the law on addendum to the [**law on audit of the Kingdom of Cambodia**]"

Do you have any idea?

**Comment by nithril** [comment]
Hi Morakort,

Sorry, I have no clue, this project and the associated knowledge is too old. You may have a look at the unit test, it may help.

**Comment by mankeomorakort** [comment]
Thank Nicolas :)
